# -*- coding: utf-8 -*-
"""Aula3Semana2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18E1c8X7bqDqTASlOYVH8RndkXEOy-Nac
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/tabela_vendas_ZePequeno_corrigido.xlsx')
df.head()

for indice, linha in df.iterrows():
  if linha['Valor_Venda']>=10000:
    print(f"A cidade {linha['Região']} atingiu a meta na data {linha['Data']}")

vendas_total = 1250  # Exemplo de valor total de uma região

for indice, linha in df.iterrows():
  vendas = linha['Valor_Venda']
  regiao = linha['Região']
  if vendas>=vendas_total:
      classificacao = "Top"
  elif vendas >= 500 and vendas<=vendas_total:
      classificacao = "Médio"
  else:
      classificacao = "Baixo"
  print(f"A região {regiao} foi classificada como: {classificacao}")

for indice, linha in df.iterrows():

    if linha["Região"] == "Sudeste":
        vendas = linha["Valor_Venda"]
        meses = 0
        while vendas < 15000:
            vendas += 2000
            meses += 1

        print(f"Na linha {indice+1} as vendas atuais foram de : R${linha["Valor_Venda"]}.")
        print(f"Será necessário {meses} meses para atingir R$15000,00")

vendas = df['Valor_Venda']

for cont, Venda in vendas.items():
  if Venda >= 10000:
    dias = df['Data']
    cidades = df['Região']
    print(f'Metas diarias batidas no dia {dias[cont].strftime('%d/%m/%Y')} na regional {cidades[cont]}')

nome=input("Qual o seu nome? ")
cidade=input("Qual a sua cidade? ")
profissao=input("Qual a sua profissão? ")
idade=int(input("Qual a sua idade? "))
salario=float(input("Qual o seu salário? "))
print(f"Nome:{type(nome)} Cidade: {type(cidade)} Profissão: {type(profissao)} Idade: {type(idade)} Salario: {type(salario)}")
print(f"Ficha cadastral - Nome: {nome}, Cidade: {cidade}, Profissão: {profissao}, Idade: {idade}, Salário: {salario}")
ano=1
while ano<=3:
  salario += 300
  ano += 1
print(f"Daqui 3 anos o salário será de {salario}")

nome=input("Qual o seu nome? ")
salario=float(input("Qual o seu salário? "))
extra=int(input("Quantidade de horas extras "))
uma_hora = (salario/220)*1.5
hora_extra = uma_hora*extra
IR=salario*0.11
salario_final = salario+hora_extra-IR
print(f"Salário final é maior que 3000? {salario_final>3000}")
print(f"Salário {salario:.2f}, hora extra {hora_extra:.2f}, IR {IR:.2f}, salario liquido {salario_final:.2f} comparação {extra>10 and salario > 2000}")

nome=input("Qual o seu nome? ")
idade=int(input("Qual a sua idade? "))
peso=float(input("Qual o seu peso? "))
altura=float(input("Qual a sua altura? "))
imc=peso/(altura**2)
if imc < 18.5:
  validar = "Abaixo do peso"
elif imc >= 18.5 and imc <= 24.9:
  validar = "Peso normal"
elif imc >=25.0 and imc <= 29.9:
  validar = "Sobrepeso"
elif imc >= 30.0 and imc <= 34.9:
  validar = "Obesidade grau 1"
elif imc >= 35.0 and imc <= 39.9:
  validar = "Obesidade grau 2"
elif imc >= 40.0:
  validar = "Obesidade grau 3"

if (imc >= 18.5 and imc <= 24.9) and idade >= 60:
  print("Atenção a saúde")

print(f"IMC esta acima de 25? {imc>=25.0}")

quant_aluno = int(input("Quantidade de alunos a ser cadastrados "))
cad_aluno = 0
aprovado = 0
recuperacao = 0
reprovado = 0
maiormedia = 0
somamedia = 0

while cad_aluno < quant_aluno:
  nome_aluno=input("Nome do aluno ")
  idade_aluno=int(input("Idade do aluno"))
  nota1=float(input("Nota 1 "))
  nota2=float(input("Nota 2 "))
  nota3=float(input("Nota 3 "))
  if nota1 < 0 or nota2 < 0 or nota3 < 0:
    continue
  media = (nota1+nota2+nota3)/3
  if media >= 7:
    final = "Aprovado"
    aprovado += 1
  elif media >= 5 and media < 7:
    final = "Recuperação"
    recuperacao += 1
  elif media < 5:
    final = "Reprovado"
    reprovado += 1
  if idade_aluno < 15 and media >= 7:
    print(f"Aluno {nome_aluno} destaque jovem!")
  if media > maiormedia:
    maior = [nome_aluno, media]
  somamedia += media
  cad_aluno += 1

mediageral = somamedia/quant_aluno
print(f"Total de alunos cadastrados {quant_aluno}.")
print(f"Quantidade de aprovados {aprovado}")
print(f"Quantidade em recuperação {recuperacao}")
print(f"Quantidade de reprovados {reprovado}")
print(f"Maior média foi de {maior[1]} do(a) aluno(a) {maior[0]}")
print(f"Média geral da turma {mediageral}")
if mediageral < 6:
  print(f"Atenção! Nota média da turma abaixo de 6")